spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:mysql:8.0:///test_container_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

testcontainers:
  reuse:
    enable: true
